#!/bin/bash
#PBS -l walltime=00:20:00
#PBS -l nodes=4:ppn=8
#PBS -N graphColoring
#PBS -j oe
#PBS -q cs

cd $PBS_O_WORKDIR
module load mpi/mpich/3.1.3-gcc-4.7.1
export OMP_NUM_THREADS=64
mpirun -np 2 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
1000_10000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/1000_10000_colored.txt
mpirun -np 2 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
1000_100000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/1000_100000_colored.txt
mpirun -np 2 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
10000_100000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/10000_100000_colored.txt
mpirun -np 2 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
10000_1000000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/10000_1000000_colored.txt

export OMP_NUM_THREADS=32
mpirun -np 4 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
1000_10000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/1000_10000_colored.txt
mpirun -np 4 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
1000_100000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/1000_100000_colored.txt
mpirun -np 4 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
10000_100000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/10000_100000_colored.txt
mpirun -np 4 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
10000_1000000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/10000_1000000_colored.txt

export OMP_NUM_THREADS=16
mpirun -np 8 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
1000_10000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/1000_10000_colored.txt
mpirun -np 8 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
1000_100000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/1000_100000_colored.txt
mpirun -np 8 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
10000_100000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/10000_100000_colored.txt
mpirun -np 8 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
10000_1000000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/10000_1000000_colored.txt

export OMP_NUM_THREADS=8
mpirun -np 16 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
1000_10000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/1000_10000_colored.txt
mpirun -np 16 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
1000_100000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/1000_100000_colored.txt
mpirun -np 16 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
10000_100000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/10000_100000_colored.txt
mpirun -np 16 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
10000_1000000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/10000_1000000_colored.txt

export OMP_NUM_THREADS=4
mpirun -np 32 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
1000_10000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/1000_10000_colored.txt
mpirun -np 32 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
1000_100000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/1000_100000_colored.txt
mpirun -np 32 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
10000_100000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/10000_100000_colored.txt
mpirun -np 32 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
10000_1000000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/10000_1000000_colored.txt

export OMP_NUM_THREADS=2
mpirun -np 64 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
1000_10000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/1000_10000_colored.txt
mpirun -np 64 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
1000_100000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/1000_100000_colored.txt
mpirun -np 64 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
10000_100000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/10000_100000_colored.txt
mpirun -np 64 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
10000_1000000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/10000_1000000_colored.txt

export OMP_NUM_THREADS=1
mpirun -np 128 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
1000_10000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/1000_10000_colored.txt
mpirun -np 128 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
1000_100000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/1000_100000_colored.txt
mpirun -np 128 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
10000_100000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/10000_100000_colored.txt
mpirun -np 128 ./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
10000_1000000.txt /home/yhtseng2/CS484-Graph-Coloring/code/parallel/output/10000_1000000_colored.txt

