#!/bin/bash
#PBS -l walltime=00:20:00
#PBS -l nodes=4:ppn=8
#PBS -N graphColoring
#PBS -j oe
#PBS -q cs

cd $PBS_O_WORKDIR
module load mpi/mpich/3.1.3-gcc-4.7.1
./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
1000_10000.txt output/1000_10000.txt
./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
1000_100000.txt output/1000_100000.txt
./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
10000_100000.txt output/10000_100000.txt
./graphColoring /home/yhtseng2/CS484-Graph-Coloring/generation/\
10000_1000000.txt output/10000_1000000.txt
